version: '3.2'
services:
    database:
        image: postgres:12
        volumes:
            - ./data/database:/var/lib/postgresql/data
        networks:
            - directus
        ports:
            - 5432:5432
        env_file: 
            - ./envs/.postgres.env

    cache:
        image: redis:6
        networks:
            - directus
        ports:
            - 6379:6379

    directus:
        image: directus/directus:v9.0.0-rc.19
        ports:
            - 8055:8055
        networks:
            - directus
        env_file: 
            - ./envs/.directus.env

networks:
    directus:
